############################################################################
############################################################################
# Job to create sample pipelines in spinnaker, useful if this job fails during
# installation.
# Simple find replace "isd" with name of the helm "release" and execute
# kubectl replace --force -f create-sample-job.yaml <-n namespace>
############################################################################
############################################################################
apiVersion: batch/v1
kind: Job
metadata:
  name: "create-apps-pipelines"
spec:
  template:
    spec:
      serviceAccountName: isd-spinnaker-halyard
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      restartPolicy: OnFailure
      volumes:
      - name: halyard-config
        configMap:
          name: isd-spinnaker-halyard-config
      - secret:
          secretName: isd-spinnaker-spin-config
        name: spin-config
      - configMap:
          defaultMode: 420
          name: isd-spinnaker-spin-pipeline-import
        name: spin-pipeline-import
      - name: spin-pipeline-config
        emptyDir: {}
      containers:
      - command:  
        - bash
        - /tmp/config/spin-pipeline-import.sh
        name: sample-pipeline-install
        image: quay.io/opsmxpublic/spin-sample-pipeline:1.0
        volumeMounts:         
        - name: spin-pipeline-config
          mountPath: /tmp/config/git
        - mountPath: /tmp/config
          name: spin-pipeline-import
        - mountPath: /tmp/config/spin
          name: spin-config
